### ISSUE TITLE
感谢作者在百忙之中抽空更新，已下载，目前Windows安全中心已经不再报毒

### ISSUE THREAD

**Issue by ShrekCharles716** [Mikachu2333/kaf-cli-gui#1]
有了可视化界面，很多自定义操作比之前的命令行好用多了，对于新手小白很友好。但使用体验感不是很好，我个人觉得需要优化一下，
1.我下载的是lite版，每次启动都会弹出弹弹窗，需要手动点击关闭，略显麻烦。可以开发一个配置文件吗，保存配置信息，例如启动弹窗只有首次使用，才会弹出
2.添加文件路径旁边，可以在加一个按钮和添加封面一样在文件管理器中选择文件。拖入方式不是很方便
3.添加封面后预览不是很人性化，这点我觉得可以去掉，或者旁边加上一个复选框让用户来选择，是否需要预览
4.kaf-cli会生成epub、azw3、mobi三种格式文本，可大部分人只需要其中一种就可以了，程序默认是all，每次启动使用需要手动选择输出格式，多了无用的步骤，可以在程序第一次启动生成配置文件，后面启动从配置文件读取用户配置
5.在选择自定义封面后，转换文本时还是会在文件目录下生成一个cover.png，不只是是不是bug
6.是否添加kaf-cli教程这个复选框是干什么的，我原以为可以去掉开头、结尾那段制作教程文字，后面试了一下，是否勾选，还是会生成制作教程那段话
以上1-5条导致使用体验感反而不如原先的命令行简单快捷

**Comment by Mikachu2333** [comment]
1.程序逻辑问题计划下一版修复
2.程序功能不完善下一版添加
3.这个个人不是很同意，暂不更改，看看以后有没有人提，提多了就改
4.每次启动？这点我不是很懂，因为在我看来使用本程序的有两种人，一种是一次性搞完所有电子书的，一种是偶尔用一次的；一直搞的无需退出软件重新设置各种参数，自然无需重复设置导出格式，另一种人偶尔用一次（比如我自己），更没有必要记着上次的参数。所以我个人并不打算另添加一个配置文件。咱本来就主打的是单文件、精简轻便，又多了个配置文件总感觉不伦不类的……
5.逻辑问题，下一版更正
6.这个暂时怀疑是原程序的错误……
证据如图所示，我写的这个gui界面传参正常，按照原作者的文档，传递false应该就能屏蔽你说的教程，但是实际上似乎并不行……
![image](https://user-images.githubusercontent.com/63829496/216349102-4f24f70b-4f2a-4076-b88e-4d37f219c877.png)
经测试，最后一页的制作教程确实无法删除……不是我这边的锅，需要原作者解决

**Comment by ShrekCharles716** [comment]
> 一种是一次性搞完所有电子书的，一种是偶尔用一次的；一直搞的无需退出软件重新设置各种参数，自然无需重复设置导出格式，另一种人偶尔用一次（比如我自己）
在我看来，还有第三种人（例如我），有仓鼠症喜欢囤积资源，时常从网上下载txt文档，转换epub格式，用苹果的图书软件阅读，使用kaf-cli的频率比较高

**Comment by ShrekCharles716** [comment]
> 一种是一次性搞完所有电子书的，一种是偶尔用一次的；一直搞的无需退出软件重新设置各种参数，自然无需重复设置导出格式，另一种人偶尔用一次（比如我自己）


在我看来，还有第三种人（例如我），有仓鼠症喜欢囤积资源，时常从网上下载txt文档，转换epub格式，用苹果的图书软件阅读，使用kaf-cli的频率比较高

**Comment by ShrekCharles716** [comment]
1.04lite版开始转换，运行kaf-cli程序时会打开一个kaf-cli-gui新窗口，转换完后kaf-cli程序自动关闭了，没有跟着关闭，需要手动关闭窗口
![image](https://user-images.githubusercontent.com/112491914/216406587-b811d2ef-8935-4f09-9069-a2ac29994c0a.png)

**Comment by ShrekCharles716** [comment]
1.04lite版开始转换，运行kaf-cli程序时会打开一个kaf-cli-gui新窗口，转换完后kaf-cli程序自动关闭了，kaf-cli-gui没有跟着关闭，需要手动关闭窗口
![image](https://user-images.githubusercontent.com/112491914/216407119-e5b82b76-f9d5-413b-83af-b1671ba04d81.png)

**Comment by ShrekCharles716** [comment]
好像不是原作者代码问题，我用命令行指令去掉了制作教程
![图片](https://user-images.githubusercontent.com/112491914/216740038-1825e022-a923-4221-95e9-0a39a59dd2a8.png)
![图片](https://user-images.githubusercontent.com/112491914/216740370-e1ab772b-3694-47b5-a4de-0d0d6db97173.png)
> kaf-cli.exe -align center -author 天一狂人 -cover 000875125.png -filename 蘑菇屋：扮演藤哥！整蛊百万观众.txt -format epub -tips=false

**Comment by Mikachu2333** [comment]
神奇的就是我所有的都没加等于号，别的指令都行，看起来就只有这个tips不加等于号用不了……

正好和下一版合并一下一并发布吧

**Comment by Mikachu2333** [comment]
现在修正了几个问题
1.不再默认为all格式了，默认为epub格式
2.自动弹窗口且不自动关闭的问题修了
3.现在改了传参测试了一下不会再出现原来的软件教程了
4.提升了版号

**Comment by ShrekCharles716** [comment]
经过几个版本的更新迭代，现在这个gui已经很好用了，目前实测这个版本没有明显的bug了，就是封面预览这个功能真不能取消吗，我个人真觉得这功能没什么意义，在选择封面的时候，Win资源管理器就已经有预览功能了，GUI节目没必要再强制加上预览功能，反而有些画蛇添足。
![image](https://user-images.githubusercontent.com/112491914/216758075-9d3c59f6-f54a-47c5-bf14-6a4d3ec713a5.png)

**Comment by Mikachu2333** [comment]
想了半天终究还是删了这个功能，主要是我自己用的不多……看起来提issue的有只有你一个，于是决定按你说的改算了

**Comment by ShrekCharles716** [comment]
目前功能已经比较完善了，随着时间的发酵，会有更多人注意到这个项目，并且使用它。作者只需在期间将界面做的更美观一些，其他的交给时间吧

**Comment by ShrekCharles716** [comment]
1.1.8 lite刚发现两个bug
1.添加封面失败
2.转换报错
![image](https://user-images.githubusercontent.com/112491914/216811745-7e9944ca-92eb-4e3a-973f-d9d657402273.png)

**Comment by Mikachu2333** [comment]
已经修复。目前看起来没什么bug了，本issues就先关掉，有新bug发新issues就是了
