### ISSUE TITLE
能否增加批量功能

### ISSUE THREAD

**Issue by letrsshub** [Mikachu2333/kaf-cli-gui#2]
我自己写了个PYTHON批处理，但是还是没有GUI舒服

**Comment by Mikachu2333** [comment]
抱歉，暂无相关计划（因为自己用的很少没啥需求，而实现起来又需要读取配置，不符合我一贯的绿色无污染宗旨（即，除了本体程序和实际调用程序以外不写任何注册表、不写任何配置文件））
